on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      KP_USER: ${{ secrets.KP_USER }}
      KP_PW: ${{ secrets.KP_PW }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::animation
            any::cfbfastR
            any::fastRhockey
            any::ggimage
            hadley/emo
            any::knitr
            any::ragg
            r-lib/pkgapi
            any::rsconnect
            any::tictoc
            any::tidyverse
            any::wehoop
            any::worldfootballR
            any::zoo
          needs: website
          dependencies: "all"

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
